---

# Ansible wants /usr/bin/python on bare Xenial
- name: Install python 2
  raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- include: ./system_dependencies.yml

# TODO: Use the iptables role

- name: Include secrets
  include_vars: secrets.yml
  no_log: true
  
# - name: Disable iptables
#   command: >
#     iptables -I INPUT -j ACCEPT
#   become: yes

# - name: Disable SELinux
#   selinux: >
#     state=disabled
#   become: yes

- name: Create Alveo data directory
  file: >
    path={{postgresql_data_directory}}
    state=directory
    owner=postgres
    group=postgres
    mode=0700
  become: yes

# - name: Stop Postgres
#   service: >
#     name=postgresql
#     state=stopped
#   become: yes

# - name: Remove old data directory
#   file: >
#     path=/var/lib/pgsql
#     state=absent
#   become: yes

# - name: Set variables in postgres startup script
#   template: >
#     src=postgresql-init.j2
#     dest=/etc/init.d/postgresql
#     owner=root
#     group=root
#   become: yes

# - name: Initialise the DB
#   command: >
#     service postgresql initdb
#   become: yes

# TODO: Copy pg_hba.conf

- name: Start Postgres
  service: >
    name=postgresql
    state=started
    enabled=yes
  become: yes

- name: Add Postgres DB
  postgresql_db: >
    name={{postgres.db}}

- name: Add Postgres user
  postgresql_user: >
    name={{postgres.user.name}}
    password={{postgres.user.password}}
    db={{postgres.db}}
