---

- name: Install required system dependencies
  yum: >
    pkg={{item}}
    state=installed
  become: yes
  with_items:
    - git
    - libselinux-python
    - python-psycopg2
    - libxml2
    - libxml2-devel
    - libxslt-devel
    - pygpgme
    - httpd
    - httpd-devel
    - nodejs
    - npm
    - postgresql93-contrib
    - postgresql93-libs
    - postgresql93-devel