---

- name: Install required system dependencies
  apt: name={{item}}
  sudo: yes
  with_items:
    - build-essential
    - git
    - python-pip
    - python-psycopg2
    - postgresql-9.3
    - libcurl4-openssl-dev
