---
# 
# Add secret stuff then encrypt using ansible-vault as secrets.yml in this directory
# http://docs.ansible.com/ansible/playbooks_vault.html
# 
galaxy_secrets:
  admin_users: 'user1@example.com,user2@example.com'