---

- name: Create solr directory
  file: >
    path={{ alveo_solr_home }}
    state=directory

- name: Copy jar files that Tomcat will need for Solr 4.3 logging
  shell: >
    cp -r {{ alveo_root }}/solr_conf/lib/ext/* {{ alveo_catalina_home }}/lib/
  sudo: yes

- name: Copy Solr core
  shell: >
    cp -r {{ alveo_root }}/solr_conf/hcsvlab {{ alveo_solr_home }}/
    creates={{alveo_solr_home}}/hcsvlab

- name: Copy hcsvlab-solr.xml to Catalina home
  template: >
    src=hcsvlab-solr.xml.j2
    dest={{ alveo_catalina_home }}/conf/Catalina/localhost/solr.xml
  sudo: yes

- name: Configure Solr
  shell: >
    cp {{ item.src }} {{ item.dest }}
  sudo: yes
  with_items:
    - { src: '{{ alveo_root }}/solr_conf/conf/schema.xml', dest: '{{ alveo_solr_home }}/hcsvlab/solr/hcsvlab-core/conf/schema.xml'}
    - { src: '{{ alveo_root }}/solr_conf/conf/solrconfig.xml', dest: '{{ alveo_solr_home }}/hcsvlab/solr/hcsvlab-core/conf/solrconfig.xml'}

- name: Ensure that solr directory has the correct permissions
  file: > 
    path={{ alveo_solr_home }}
    recurse=yes
    owner=tomcat
    group=tomcat
  sudo: yes