---
- name: Ensure Tomcat6 packages are installed (RedHat).
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - tomcat6
    - tomcat6-webapps
    - tomcat6-admin-webapps
  when: ansible_os_family == 'RedHat'
  sudo: yes

- name: Update apt cache (Debian).
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Ensure Tomcat6 is installed (Debian).
  apt:
    name: tomcat6
    state: installed
  when: ansible_os_family == 'Debian'

- name: Configure Tomcat6
  template: >
    src=tomcat6.config.j2
    dest=/etc/sysconfig/tomcat6
  notify: restart tomcat6
  sudo: yes

- name: Ensure tomcat6 is running.
  service:
    name: tomcat6
    state: started
    enabled: yes
  when: tomcat6_enabled
  sudo: yes