---

alveo:
  home: /home/devel/alveo
  repo: https://github.com/Alveo/hcsvlab.git
  version: HEAD
  rails_env: production
  server: alveo.example.com

postgresql_data_directory: alveo
postgresql_base_directory: /mnt/data/pgsql
postgresql_conf_directory: /mnt/data/pgsql/alveo
postgresql_bin_directory: /usr/pgsql-9.3/bin

postgresql_listen_addresses:
  - '*'

# db creds and hosts moved to secrets.yml

postgresql_locale: en_AU.UTF-8

#------------------------------------------------------------------------------
# RESOURCE USAGE (except WAL)
#------------------------------------------------------------------------------

# - Memory -

postgresql_shared_buffers:       2560MB # min 128kB
postgresql_temp_buffers:         128MB   # min 800kB

# Note:  Increasing max_prepared_transactions costs ~600 bytes of shared memory
# per transaction slot, plus lock space (see max_locks_per_transaction).
# It is not advisable to set max_prepared_transactions nonzero unless you
# actively intend to use prepared transactions.
postgresql_max_prepared_transactions: 0 # zero disables the feature

postgresql_work_mem:             16MB   # min 64kB
postgresql_maintenance_work_mem: 256MB  # min 1MB
postgresql_max_stack_depth:      8MB   # min 100kB
