postgresql_databases:
  - name: hcsvlab

# List of users to be created (optional)
postgresql_users:
  - name: hcsvlab
    pass: hcsvlab
    encrypted: no       # denotes if the password is already encrypted.

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: hcsvlab         # user name
    db: hcsvlab         # database
    priv: "ALL"

postgresql_pg_hba_trust_hosts:
  - '172.16.4.140/24'

postgres:
  db: hcsvlab
  user:
    name: hcsvlab
    password: hcsvlab