---

- name: Install required system dependencies
  yum: pkg={{item}} state=installed
  sudo: yes
  with_items:
    - git
    - unzip
    - tar
    - gzip
    - libselinux-python
    - "@Development tools"
